=== airavata-courses/TeamIndra/Gateway First Tier/src/main/resources/config/pbs_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/pbs_config"
	xmlns:tns="http://www.example.org/pbs_config" elementFormDefault="qualified">

	<complexType name="parameter_type">
		<sequence>
			<element name="name" type="string"></element>
			<element name="command" type="string"></element>
			<element name="type" type="string"></element>
			<element name="desc" type="string"></element>
			<element name="default" type="string"></element>
		</sequence>
	</complexType>

	<element name="script" type="tns:script_type"></element>

	<complexType name="script_type">
		<sequence>
			<element name="parameters" type="tns:parameter_type"
				maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>

	</complexType>

</schema>

=== airavata-courses/TeamIndra/Gateway First Tier/src/main/resources/config/karst_pbs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:script xmlns:tns="http://www.example.org/pbs_config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/pbs_config pbs_config.xsd ">
	<tns:parameters>
		<tns:name>Queue</tns:name>
		<tns:command>q</tns:command>
		<tns:desc>Queue in which job will be placed</tns:desc>
		<tns:default>normal</tns:default>
	</tns:parameters>
	<tns:parameters>
		<tns:name>Mail</tns:name>
		<tns:command>m</tns:command>
		<tns:desc>Send email on job status change</tns:desc>
		<tns:default></tns:default>
	</tns:parameters>
	<tns:parameters>
		<tns:name>Name</tns:name>
		<tns:command>N</tns:command>
		<tns:desc>Name of job</tns:desc>
		<tns:default>test</tns:default>
	</tns:parameters>
	<tns:parameters>
		<tns:name>Memory Limit</tns:name>
		<tns:command>l mem</tns:command>
		<tns:desc>Queue in which job will be placed</tns:desc>
		<tns:default>normal</tns:default>
	</tns:parameters>
</tns:script>
